project_id = "mekwfbqmsqiborjdrjxc"

[functions.greenapi-webhook]
verify_jwt = false

[functions.ai-rop-analyze-chat]
verify_jwt = false

[functions.ai-rop-analyze-call]
verify_jwt = false

[functions.sipuni-cdr-webhook]
verify_jwt = false

[functions.ai-rop-score-manager]
verify_jwt = false

[functions.ai-rop-generate-script]
verify_jwt = false

[functions.ai-rop-generate-content]
verify_jwt = false
