import type React from "react";
import { Composition } from "remotion";
import { Main169 } from "./Main169";
import type { MainProps } from "./Main169";
import { Shorts916 } from "./Shorts916";
import type { ShortsProps } from "./Shorts916";
import { MotionDemo, MOTION_DEMO_DURATION } from "./MotionDemo";
// Example props so Studio runs out of the box. Real props are generated by the
// pipeline (pipeline/props.py → props/main169.json, pipeline/shorts.py → props/<id>.json).
import mainExample from "../props/main169.example.json";
import shortExample from "../props/short.example.json";
import short8501b3ac from "../props/Short-8501b3ac.json";

const defaultMainProps = mainExample as unknown as MainProps;
const defaultShortProps = shortExample as unknown as ShortsProps;
const short8501b3acProps = short8501b3ac as unknown as ShortsProps;

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="Main169"
        component={Main169}
        durationInFrames={defaultMainProps.totalDurationInFrames}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={defaultMainProps}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
      <Composition
        id="Short-Example"
        component={Shorts916}
        durationInFrames={defaultShortProps.totalDurationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={defaultShortProps}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
      <Composition
        id="MotionDemo"
        component={MotionDemo}
        durationInFrames={MOTION_DEMO_DURATION}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="Short-8501b3ac"
        component={Shorts916}
        durationInFrames={short8501b3acProps.totalDurationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={short8501b3acProps}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
    </>
  );
};
