import type React from "react";
import { Composition } from "remotion";
import { Main169 } from "./Main169";
import type { MainProps } from "./Main169";
import { Shorts916 } from "./Shorts916";
import type { ShortsProps } from "./Shorts916";
import { MotionDemo, MOTION_DEMO_DURATION } from "./MotionDemo";
import { ReelsExplainer } from "./ReelsExplainer";
import type { ReelsExplainerProps } from "./ReelsExplainer";
import { ReelsAvatar } from "./ReelsAvatar";
import type { ReelsAvatarProps } from "./ReelsAvatar";
import { Split5050 } from "./Split5050";
import type { SplitProps } from "./Split5050";
// Example props so Studio runs out of the box. Real props are generated by the
// pipeline (pipeline/props.py → props/main169.json, pipeline/shorts.py → props/<id>.json).
import mainExample from "../props/main169.example.json";
import shortExample from "../props/short.example.json";
import short8501b3ac from "../props/Short-8501b3ac.json";
import reels009 from "../props/Reels-009fc34b.json";
import reelsAvatarExample from "../props/reels-avatar.example.json";
import split5050Demo from "../props/split5050.demo.json";
import shortD312Full from "../props/Short-d312-full.json";
import shortD312Punch from "../props/Short-d312-punch.json";

const defaultMainProps = mainExample as unknown as MainProps;
const defaultShortProps = shortExample as unknown as ShortsProps;
const short8501b3acProps = short8501b3ac as unknown as ShortsProps;
const reels009Props = reels009 as unknown as ReelsExplainerProps;
const reelsAvatarProps = reelsAvatarExample as unknown as ReelsAvatarProps;
const split5050Props = split5050Demo as unknown as SplitProps;
const shortD312FullProps = shortD312Full as unknown as ShortsProps;
const shortD312PunchProps = shortD312Punch as unknown as ShortsProps;

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="Main169"
        component={Main169}
        durationInFrames={defaultMainProps.totalDurationInFrames}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={defaultMainProps}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
      <Composition
        id="Short-Example"
        component={Shorts916}
        durationInFrames={defaultShortProps.totalDurationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={defaultShortProps}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
      <Composition
        id="ReelsExplainer"
        component={ReelsExplainer}
        durationInFrames={reels009Props.totalDurationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={reels009Props}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
      {/* Контент-завод: говорящая голова поверх анимации, 4 раскладки.
          Пропсы на каждый ролик пачки — work/factory/<project>/batches/<b>/scenes/<id>.json. */}
      <Composition
        id="ReelsAvatar"
        component={ReelsAvatar}
        durationInFrames={reelsAvatarProps.totalDurationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={reelsAvatarProps}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
      <Composition
        id="Split5050"
        component={Split5050}
        durationInFrames={split5050Props.totalDurationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={split5050Props}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
      <Composition
        id="MotionDemo"
        component={MotionDemo}
        durationInFrames={MOTION_DEMO_DURATION}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="Short-8501b3ac"
        component={Shorts916}
        durationInFrames={short8501b3acProps.totalDurationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={short8501b3acProps}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
      <Composition
        id="Short-d312-full"
        component={Shorts916}
        durationInFrames={shortD312FullProps.totalDurationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={shortD312FullProps}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
      <Composition
        id="Short-d312-punch"
        component={Shorts916}
        durationInFrames={shortD312PunchProps.totalDurationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={shortD312PunchProps}
        calculateMetadata={({ props }) => ({
          durationInFrames: props.totalDurationInFrames,
        })}
      />
    </>
  );
};
